/**
 * Generic LLM Agent v1 - AI-Powered Coding Assistant
 * Uses Google Gemini to generate code from natural language tasks
 *
 * Environment Variables Required:
 * - GEMINI_API_KEY: Google AI API key for Gemini access
 * - TASK_DESCRIPTION: Natural language description of the task
 * - TASK_ID: Unique identifier for the task
 */

import { GoogleGenerativeAI } from "@google/generative-ai";

interface TaskOutput {
  success: boolean;
  result?: string;
  code?: string;
  error?: string;
}

async function main() {
  console.log("[LLM-AGENT-V1] 🚀 Initializing Generic LLM Agent...");

  // Read environment variables
  const apiKey = process.env.GEMINI_API_KEY;
  const taskDescription = process.env.TASK_DESCRIPTION || "No task provided";
  const taskId = process.env.TASK_ID || "unknown";

  // Validate API key
  if (!apiKey) {
    const output: TaskOutput = {
      success: false,
      error:
        "GEMINI_API_KEY environment variable not set. Cannot proceed without API credentials.",
    };
    console.error("[LLM-AGENT-V1] ❌ CRITICAL ERROR:", output.error);
    console.log(JSON.stringify(output));
    process.exit(1);
  }

  try {
    console.log(`[LLM-AGENT-V1] 📋 Processing Task ID: ${taskId}`);
    console.log(`[LLM-AGENT-V1] 💭 Task Description: "${taskDescription}"`);

    // Initialize Google Generative AI
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });

    // Construct expert prompt
    const prompt = `You are an expert programmer with deep knowledge across multiple languages and paradigms.

TASK: ${taskDescription}

INSTRUCTIONS:
1. Generate clean, production-ready code that fully implements the requested functionality
2. Use best practices and modern idioms for the target language
3. Include helpful inline comments explaining complex logic
4. Ensure the code is complete and runnable
5. If the task is ambiguous, make reasonable assumptions and document them

IMPORTANT: Provide ONLY the code. No markdown formatting, no explanations outside the code, no extra commentary.

Generate the code now:`;

    console.log("[LLM-AGENT-V1] 🤖 Calling Gemini AI...");

    // Call Gemini API
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const generatedCode = response.text();

    // Validate response
    if (!generatedCode || generatedCode.trim().length === 0) {
      throw new Error("Gemini returned empty response");
    }

    // Clean up code (remove markdown code fences if present)
    let cleanCode = generatedCode.trim();
    if (cleanCode.startsWith("```")) {
      // Remove opening fence
      cleanCode = cleanCode.replace(/^```[a-zA-Z]*\n/, "");
      // Remove closing fence
      cleanCode = cleanCode.replace(/\n```$/, "");
    }

    // Output successful result
    const output: TaskOutput = {
      success: true,
      result: `Code successfully generated by Gemini AI for task: ${taskDescription}`,
      code: cleanCode,
    };

    console.log("[LLM-AGENT-V1] ✅ Task completed successfully!");
    console.log(
      `[LLM-AGENT-V1] 📊 Generated ${cleanCode.split("\n").length} lines of code`
    );
    console.log(JSON.stringify(output, null, 2));
    process.exit(0);
  } catch (error) {
    // Handle errors gracefully
    const errorMessage = error instanceof Error ? error.message : String(error);
    const output: TaskOutput = {
      success: false,
      error: `Gemini API call failed: ${errorMessage}`,
    };

    console.error("[LLM-AGENT-V1] ❌ ERROR:", errorMessage);

    // Provide detailed error context for debugging
    if (error instanceof Error && error.stack) {
      console.error("[LLM-AGENT-V1] Stack trace:", error.stack);
    }

    console.log(JSON.stringify(output));
    process.exit(1);
  }
}

// Execute main function
main().catch((error) => {
  console.error("[LLM-AGENT-V1] 💥 Unhandled error in main:", error);
  process.exit(1);
});
