/**
 * Represents the multi-dimensional nature of a developer's request.
 * This is the primary input that triggers the Economic Genesis Engine.
 */
export interface TaskVector {
  id: string;
  timestamp: number;
  sourceCode: string;
  naturalLanguageIntent: string;
  parsedIntent: {
    primaryAction:
      | "CREATE"
      | "TEST"
      | "REFACTOR"
      | "DEBUG"
      | "DOCUMENT"
      | "RESEARCH";
    subject: string;
    context: string[];
  };
  projectContext: {
    projectId: string;
    filePath: string;
    projectStyleGuide: Record<string, unknown>;
  };
  constraints: {
    maxBudget: number;
    maxTimeSeconds: number;
    requiredCredibility: number;
  };
}
/**
 * Defines the profile and capabilities of a specialized agent.
 */
export interface AgentProfile {
  id: string;
  archetype: "Sentinel" | "Scout" | "Alchemist" | "Drone";
  specializations: string[];
  costPerToken: number;
  costPerSecond: number;
}
/**
 * Tracks the dynamic trust and reputation of an agent instance.
 */
export interface AgentCredibility {
  agentId: string;
  score: number;
  history: Array<{
    taskId: string;
    outcome: "SUCCESS" | "FAILURE" | "REJECTED";
    credibilityChange: number;
    timestamp: number;
  }>;
}
/**
 * A plan generated by the Economic Genesis Engine before execution.
 */
export interface ExecutionPlan {
  planId: string;
  taskId: string;
  swarm: Array<{
    agentProfile: AgentProfile;
    taskChunk: string;
  }>;
  estimatedBudget: number;
  estimatedTimeSeconds: number;
}
/**
 * A receipt logged after an execution plan is completed or terminated.
 * Used for Swarm-Healing and updating the Agent Credibility Engine.
 */
export interface ExecutionReceipt {
  receiptId: string;
  planId: string;
  taskId: string;
  outcome: "COMPLETED" | "FAILED" | "CANCELLED";
  finalCost: number;
  finalTimeSeconds: number;
  results: Array<{
    agentId: string;
    output: string;
    wasAccepted: boolean;
  }>;
  failureAnalysis?: {
    failedAgentId: string;
    reason: string;
    logs: string;
  };
}
