// packages/nexus-core/src/cognitive.types.ts

/**
 * Represents the multi-dimensional nature of a developer's request.
 * This is the primary input that triggers the Economic Genesis Engine.
 */
export interface TaskVector {
  id: string;
  timestamp: number;
  sourceCode: string; // The highlighted code block or file content
  naturalLanguageIntent: string; // The developer's raw command
  parsedIntent: {
    primaryAction: 'CREATE' | 'TEST' | 'REFACTOR' | 'DEBUG' | 'DOCUMENT' | 'RESEARCH';
    subject: string; // e.g., "unit tests", "performance", "this function"
    context: string[]; // Keywords derived from surrounding code
  };
  projectContext: {
    projectId: string;
    filePath: string;
    projectStyleGuide: Record<string, any>; // A summary from the Personal En-gram
  };
  constraints: {
    maxBudget: number; // Max computational cost
    maxTimeSeconds: number;
    requiredCredibility: number; // Minimum agent credibility required
  };
}

/**
 * Defines the profile and capabilities of a specialized agent.
 */
export interface AgentProfile {
  id: string;
  archetype: 'Sentinel' | 'Scout' | 'Alchemist' | 'Drone';
  specializations: string[]; // e.g., ["Jest", "React", "SQL Injection"]
  costPerToken: number;
  costPerSecond: number;
}

/**
 * Tracks the dynamic trust and reputation of an agent instance.
 */
export interface AgentCredibility {
  agentId: string;
  score: number; // A value between 0.0 and 1.0
  history: Array<{
    taskId: string;
    outcome: 'SUCCESS' | 'FAILURE' | 'REJECTED';
    credibilityChange: number;
    timestamp: number;
  }>;
}

/**
 * A plan generated by the Economic Genesis Engine before execution.
 */
export interface ExecutionPlan {
  planId: string;
  taskId: string;
  swarm: Array<{
    agentProfile: AgentProfile;
    taskChunk: string; // The specific sub-task for this agent
  }>;
  estimatedBudget: number;
  estimatedTimeSeconds: number;
}

/**
 * A receipt logged after an execution plan is completed or terminated.
 * Used for Swarm-Healing and updating the Agent Credibility Engine.
 */
export interface ExecutionReceipt {
  receiptId: string;
  planId: string;
  taskId: string;
  outcome: 'COMPLETED' | 'FAILED' | 'CANCELLED';
  finalCost: number;
  finalTimeSeconds: number;
  results: Array<{
    agentId: string;
    output: string;
    wasAccepted: boolean;
  }>;
  failureAnalysis?: {
    failedAgentId: string;
    reason: string;
    logs: string;
  };
}
